### ISSUE TITLE
Unknown blueprint: ember-cli-rx

### ISSUE THREAD

**Issue by gnapse** [blesh/ember-cli-rx#1]
I followed the install instructions in the README, and on the second comand I get an error:

```
$ npm install --save-dev ember-cli-rx
ember-cli-rx@0.0.0 node_modules/ember-cli-rx

$ ember generate ember-cli-rx
version: 0.1.6
Unknown blueprint: ember-cli-rx
```

Any comments on that?

**Comment by machty** [comment]
@gnapse we still need to publish everything to npm, but if you use master are you still getting this error? I can't reproduce.

**Comment by benlesh** [comment]
poke @gnapse ... I also couldn't get this to reproduce. Perhaps it was a bad npm install?

**Comment by jayphelps** [comment]
This was related to it being `0.0.0`. Fixed now that we're cutting proper releases.

**Comment by benlesh** [comment]
Okay, closing this then.
