### ISSUE TITLE
Properly publish all releases to npm

### ISSUE THREAD

**Issue by jayphelps** [blesh/ember-cli-rx#5]
None of the releases have been properly published to npm. Please back-publish all the releases.

``` bash
$ npm view ember-cli-rx versions
0.0.0
```

I don't have npm rights, otherwise I'd do it :o)

**Comment by machty** [comment]
@jayphelps I believe this is done now, can you confirm?

**Comment by jayphelps** [comment]
@machty Yep, thank you! I would suggest [deprecating](https://docs.npmjs.com/cli/deprecate) the `0.0.0` version that is still published so people start getting correct semver semantics.

**Comment by machty** [comment]
Deprecated, thanks!
