### ISSUE TITLE
Need to update RxJS to 2.4.X

### ISSUE THREAD

**Issue by benlesh** [blesh/ember-cli-rx#6]
There's no reason not to update. This shouldn't be a big deal.

**Comment by benlesh** [comment]
Also need this to stop the bower nagging here. https://github.com/Netflix/ember-cli-nf-graph/issues/19

I dislike bower.

**Comment by benlesh** [comment]
Actually, updating to 2.5.X (latest)

**Comment by jayphelps** [comment]
This can be closed. https://github.com/blesh/ember-cli-rx/commit/078755e7cc5a2405e5f8a83eb55e593e84fe096b
